### ISSUE TITLE
Create a jenkins.yaml for our casc.praqma.cloud demo

### ISSUE THREAD

**Issue by MadsNielsen** [Praqma/praqma-jenkins-casc#3]

**Comment by buep** [comment]
The Jenkins instance should have the following traits:

* no one can edit anything
* public read
* should point to two real jobs in the seed-job part
* should have one slave
* should point to docs about this demo setup in the welcome message

**Comment by buep** [comment]
Related to https://github.com/Praqma/praqma-jenkins-casc/issues/8

**Comment by MadsNielsen** [comment]
demoAdmin can admin everything for now and i've commented out the slaves until we've got some online we can connect.
