### ISSUE TITLE
Demo projects for casc. Find and configure a good second example project

### ISSUE THREAD

**Issue by MadsNielsen** [Praqma/praqma-jenkins-casc#7]
We want to add some intial projects to jcasc. We discussed it and we decided that we want to have a couple of examples on how to do this.

Then entry point will be the `jenkins.yaml` file where we define the initial seeds jobs in the `jobs` root element: 

```
jenkins:
 [...]
jobs: 
 [...]
``` 
This can be seen as a subtask of #3 

This is about figuring out the second demo job we want to use, we'll use jcasc itself as an example, to which you can already copy paste the yaml from the plugin source, so the task of this is to find a good second example project that demonstrates typical use.

**Comment by buep** [comment]
Related to https://github.com/Praqma/praqma-jenkins-casc/issues/8

**Comment by MadsNielsen** [comment]
First part done.

I've created a project with the purpose of demoing some of the features we've added. 

- Warnings plugin 
- Shared pipeline libraries: https://github.com/Praqma/praqma-jenkins-casc-shared-lib-demo

Missing: 
- [ ] Real world example? Existing project?

**Comment by MadsNielsen** [comment]
build our own plugin is blocked by https://github.com/jenkinsci/configuration-as-code-plugin/issues/170
